font_size        15

background_opacity 0.9
foreground       #FFA500

shell_integration no-cursor
cursor_shape block
cursor_blink_interval     0.5
cursor_stop_blinking_after 15.0

scrollback_lines	5000
remember_window_size no
initial_window_width 1100
initial_window_height 600

tab_bar_style slant


# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
