font_size        15

background_opacity 0.9
foreground       #FFA500

shell_integration no-cursor
cursor_shape block
cursor_blink_interval     0.5
cursor_stop_blinking_after 15.0

scrollback_lines	5000
remember_window_size no
initial_window_width 1100
initial_window_height 600

tab_bar_style slant


# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Open new tab in current directory
map ctrl+shift+t new_tab_with_cwd

# Reset the terminal
map f1 clear_terminal reset active
# Clear the terminal screen by erasing all contents
map f1 clear_terminal clear active
# Clear the terminal scrollback by erasing it
map f1 clear_terminal scrollback active
# Scroll the contents of the screen into the scrollback
map f1 clear_terminal scroll active
# Clear everything on screen up to the line with the cursor or the start of the current prompt (needs shell integration)
map f1 clear_terminal to_cursor active
# Same as above except cleared lines are moved into scrollback
map f1 clear_terminal to_cursor_scroll active
# Erase the last command and its output (needs shell integration to work)
map f1 clear_terminal last_command active
