## COLORS
foreground #f7f1ff
background #0a0a0a
cursor #f7f1ff

## TAB COLORS
active_tab_foreground   #FFED29
active_tab_background   #090909
active_tab_font_style   bold-italic
inactive_tab_foreground #444
inactive_tab_background #181818
inactive_tab_font_style normal

font_size        15
#background_image /run/media/eu/HDD/Wallpapers/Wallpapers/wallpaperflare.com_wallpaper.jpg
background_image_layout cscaled
background_image_linear yes
background_tint 0.8
background_opacity 0.9

allow_remote_control yes
shell_integration no-cursor
cursor_shape block
cursor_blink_interval     0.5
cursor_stop_blinking_after 15.0
confirm_os_window_close 1
cursor_trail 1
#cursor_shape beam
cursor_shape block
cursor_beam_thickness 4
cursor_stop_blinking_after 0
cursor_shape_unfocused unchanged
window_margin_width     5
#os_window_state fullscreen

scrollback_lines	5000
remember_window_size no
initial_window_width 1070
initial_window_height 600

tab_bar_style       powerline
tab_powerline_style slanted

# BEGIN_KITTY_FONTS
font_family      family="Consolas Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Open new tab in current directory
map ctrl+shift+t new_tab_with_cwd

# Reset the terminal
map f1 clear_terminal reset active
# Clear the terminal screen by erasing all contents
map f1 clear_terminal clear active
# Clear the terminal scrollback by erasing it
map f1 clear_terminal scrollback active
# Scroll the contents of the screen into the scrollback
map f1 clear_terminal scroll active
# Clear everything on screen up to the line with the cursor or the start of the current prompt (needs shell integration)
map f1 clear_terminal to_cursor active
# Same as above except cleared lines are moved into scrollback
map f1 clear_terminal to_cursor_scroll active
# Erase the last command and its output (needs shell integration to work)
map f1 clear_terminal last_command active
