"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$directory$character'

add_newline = true

[character]
success_symbol = '[λ](bold yellow)'
error_symbol = '[λ](bold red)'

[package]
disabled = true
