"$schema" = 'https://starship.rs/config-schema.json'

palette = "redteam"

add_newline = false
format = "$username$directory$git_branch$git_status$character"

[palettes.redteam]
bg1 = "#0a0a0a"
bg2 = "#111111"
bg3 = "#1a1a1a"
bg4 = "#220000"

fg = "#eaeaea"
red = "#ff003c"
neon = "#00ff9c"
gray = "#666666"

[character]
success_symbol = "[❯](bold neon)"
error_symbol = "[❯](bold red)"

[username]
show_always = false
format = "[ ☠ $user]($style)"
style_user = "fg:white bold"
style_root = "fg:red bold"

[directory]
style = "fg:blue bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:neon"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:red bold"
format = "[($all_status$ahead_behind)]($style)"

[package]
disabled = true

[line_break]
disabled = true
